[package]
name = "easyexcel-rocket"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "easyexcel-support rocket adapter for easyexcel-rust"
repository.workspace = true

[dependencies]
easyexcel = { workspace = true }
easyexcel-web = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
rocket = { workspace = true }
serde_json = { workspace = true }
tokio-util = { workspace = true }
urlencoding = { workspace = true }

[lints]
workspace = true
