//! Mirrors the `ExcelRow` interface generated by `#[derive(ExcelRow)]`.

use crate::analysis_context::Result;
use crate::converter_registry::ConverterRegistry;
use crate::excel_column::ExcelColumn;
use crate::excel_write_metadata::ExcelWriteMetadata;
use crate::row_data::RowData;
use crate::{CellValue, WriteCellData};

/// Compile-time mapping implemented by `#[derive(ExcelRow)]`.
///
/// Java exposes the same five entry points on the
/// `com.alibaba.excel.metadata.ModelBuildEventListener` /
/// `AbstractHolder` runtime reflection path. Rust moves all five to the
/// `ExcelRow` trait so the [`easyexcel-derive`] macro can generate the impl
/// at compile time.
pub trait ExcelRow: Sized {
    /// Returns static column metadata. (Java `ExcelHeadProperty.getHeadMap().values()`)
    fn schema() -> &'static [ExcelColumn];

    /// Returns whether this item represents a Java `null` row.
    ///
    /// Writers advance the physical and relative row indexes for an absent row,
    /// but do not create a row, run conversion, or invoke row/cell handlers.
    #[must_use]
    fn is_absent_row(&self) -> bool {
        false
    }

    /// Returns annotation-driven dimensions used by writers. (Java
    /// `ExcelWriteHeadProperty`)
    #[must_use]
    fn write_metadata() -> &'static ExcelWriteMetadata {
        const METADATA: ExcelWriteMetadata = ExcelWriteMetadata::new();
        &METADATA
    }

    /// Converts a physical row into the user type. (Java `ModelBuildEventListener.buildUserModel`)
    ///
    /// # Errors
    ///
    /// Returns a location-aware conversion error when any field cannot be decoded.
    fn from_row(row: &RowData) -> Result<Self>;

    /// Converts a physical row using Java-style globally registered converters.
    /// (Java `ModelBuildEventListener` with `ConverterRegistry`)
    ///
    /// # Errors
    ///
    /// Returns a location-aware conversion error.
    fn from_row_with_converters(row: &RowData, _converters: &ConverterRegistry) -> Result<Self> {
        Self::from_row(row)
    }

    /// Converts the user type into schema-ordered cells.
    ///
    /// # Errors
    ///
    /// Returns an error when any field cannot be encoded as an Excel cell.
    fn to_row(&self) -> Result<Vec<crate::cell_value::CellValue>>;

    /// Converts the value using Java-style globally registered converters.
    ///
    /// # Errors
    ///
    /// Returns an error when a field cannot be represented as an Excel cell.
    fn to_row_with_converters(
        &self,
        _converters: &ConverterRegistry,
    ) -> Result<Vec<crate::cell_value::CellValue>> {
        self.to_row()
    }

    /// Returns both pre-converter field values and converted cell values.
    ///
    /// Derive-generated implementations evaluate the normal field encoding
    /// before the converter chain, matching Java `converterAndSet`. Manual
    /// implementations default to `to_row()` plus `to_row_with_converters()`.
    ///
    /// # Errors
    ///
    /// Returns an error when either representation cannot be produced.
    fn to_excel_write_row(
        &self,
        converters: &ConverterRegistry,
    ) -> Result<(Vec<CellValue>, Vec<WriteCellData>)> {
        Ok((
            self.to_row()?,
            self.to_row_with_converters(converters)?
                .into_iter()
                .map(WriteCellData::new)
                .collect(),
        ))
    }

    /// Converts only the requested schema positions for a filtered write.
    ///
    /// Java removes excluded fields from `FieldCache.sortedFieldMap` before
    /// `ExcelWriteAddExecutor` invokes converters. Derive-generated
    /// implementations therefore skip conversion entirely for positions that
    /// are not selected. Manual implementations retain the compatibility
    /// default and blank excluded results after conversion.
    ///
    /// # Errors
    ///
    /// Propagates the error from [`IntoExcelCell::to_excel_write_row`] when
    /// the underlying conversion fails.
    fn to_excel_write_row_selected(
        &self,
        converters: &ConverterRegistry,
        selected_schema_indexes: Option<&[usize]>,
    ) -> Result<(Vec<CellValue>, Vec<WriteCellData>)> {
        let (mut original, mut converted) = self.to_excel_write_row(converters)?;
        if let Some(selected) = selected_schema_indexes {
            for (index, value) in original.iter_mut().enumerate() {
                if !selected.contains(&index) {
                    *value = CellValue::Empty;
                }
            }
            for (index, value) in converted.iter_mut().enumerate() {
                if !selected.contains(&index) {
                    *value = WriteCellData::new(CellValue::Empty);
                }
            }
        }
        Ok((original, converted))
    }
}

impl<T> ExcelRow for Option<T>
where
    T: ExcelRow,
{
    fn schema() -> &'static [ExcelColumn] {
        T::schema()
    }

    fn is_absent_row(&self) -> bool {
        self.is_none()
    }

    fn write_metadata() -> &'static ExcelWriteMetadata {
        T::write_metadata()
    }

    fn from_row(row: &RowData) -> Result<Self> {
        T::from_row(row).map(Some)
    }

    fn from_row_with_converters(row: &RowData, converters: &ConverterRegistry) -> Result<Self> {
        T::from_row_with_converters(row, converters).map(Some)
    }

    fn to_row(&self) -> Result<Vec<CellValue>> {
        self.as_ref()
            .map_or_else(|| Ok(Vec::new()), ExcelRow::to_row)
    }

    fn to_row_with_converters(&self, converters: &ConverterRegistry) -> Result<Vec<CellValue>> {
        self.as_ref().map_or_else(
            || Ok(Vec::new()),
            |row| row.to_row_with_converters(converters),
        )
    }

    fn to_excel_write_row(
        &self,
        converters: &ConverterRegistry,
    ) -> Result<(Vec<CellValue>, Vec<WriteCellData>)> {
        self.as_ref().map_or_else(
            || Ok((Vec::new(), Vec::new())),
            |row| row.to_excel_write_row(converters),
        )
    }

    fn to_excel_write_row_selected(
        &self,
        converters: &ConverterRegistry,
        selected_schema_indexes: Option<&[usize]>,
    ) -> Result<(Vec<CellValue>, Vec<WriteCellData>)> {
        self.as_ref().map_or_else(
            || Ok((Vec::new(), Vec::new())),
            |row| row.to_excel_write_row_selected(converters, selected_schema_indexes),
        )
    }
}

#[cfg(test)]
mod tests_extra {
    use super::*;

    /// 对应 Java：最小测试模型，实现 `ExcelRow` 五入口
    #[derive(Clone, Debug, PartialEq)]
    struct ProbeRow;

    impl ExcelRow for ProbeRow {
        fn schema() -> &'static [ExcelColumn] {
            &[]
        }

        fn from_row(_row: &RowData) -> Result<Self> {
            Ok(ProbeRow)
        }

        fn to_row(&self) -> Result<Vec<CellValue>> {
            Ok(vec![CellValue::Int(1)])
        }
    }

    fn sample_row() -> RowData {
        RowData::new(
            "Sheet1",
            0,
            Vec::new(),
            std::sync::Arc::new(std::collections::HashMap::new()),
        )
    }

    #[test]
    fn option_some_delegates_to_inner_model() {
        // 对应 Java：Option<T> 委托给内部模型
        let row = sample_row();
        let some: Option<ProbeRow> = Option::from_row(&row).expect("converts");
        assert_eq!(some, Some(ProbeRow));

        let converters = ConverterRegistry::default();
        let some_converters: Option<ProbeRow> =
            Option::from_row_with_converters(&row, &converters).expect("converts");
        assert_eq!(some_converters, Some(ProbeRow));

        assert_eq!(some.to_row().expect("ok"), vec![CellValue::Int(1)]);
        assert_eq!(
            some.to_row_with_converters(&converters).expect("ok"),
            vec![CellValue::Int(1)]
        );
        let (original, converted) = some.to_excel_write_row(&converters).expect("ok");
        assert_eq!(original, vec![CellValue::Int(1)]);
        assert_eq!(converted.len(), 1);
        let (selected_original, selected_converted) = some
            .to_excel_write_row_selected(&converters, Some(&[0]))
            .expect("ok");
        assert_eq!(selected_original, vec![CellValue::Int(1)]);
        assert_eq!(selected_converted.len(), 1);
    }

    #[test]
    fn option_none_returns_empty_results() {
        // 对应 Java：null 行跳过转换返回空
        let none: Option<ProbeRow> = None;
        let converters = ConverterRegistry::default();
        assert_eq!(none.to_row().expect("ok"), Vec::<CellValue>::new());
        assert_eq!(
            none.to_row_with_converters(&converters).expect("ok"),
            Vec::<CellValue>::new()
        );
        let (original, converted) = none.to_excel_write_row(&converters).expect("ok");
        assert!(original.is_empty());
        assert!(converted.is_empty());
        let (original, converted) = none
            .to_excel_write_row_selected(&converters, Some(&[0]))
            .expect("ok");
        assert!(original.is_empty());
        assert!(converted.is_empty());
        assert!(none.is_absent_row());
    }

    #[test]
    fn option_none_to_excel_write_row_selected_without_selection() {
        // 对应 Java：无选区时同样返回空
        let none: Option<ProbeRow> = None;
        let converters = ConverterRegistry::default();
        let (original, converted) = none
            .to_excel_write_row_selected(&converters, None)
            .expect("ok");
        assert!(original.is_empty());
        assert!(converted.is_empty());
    }

    #[test]
    fn option_delegates_schema_and_metadata() {
        // 对应 Java：Option<T> 的 schema 与写元数据透传
        assert!(Option::<ProbeRow>::schema().is_empty());
        let _ = Option::<ProbeRow>::write_metadata();
        assert!(Option::<ProbeRow>::is_absent_row(&None));
        assert!(!Option::<ProbeRow>::is_absent_row(&Some(ProbeRow)));
    }
}
