[package]
name = "easyexcel-support-salvo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "easyexcel-support salvo adapter for easyexcel-rust"
repository.workspace = true

[dependencies]
easyexcel = { workspace = true }
easyexcel-core = { workspace = true }
salvo = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
urlencoding = { workspace = true }

[lints]
workspace = true
