//! 对应 Java：`com.alibaba.excel.constant.*`.

pub mod builtin_formats;
pub mod easy_excel_constants;
pub mod excel_xml_constants;
pub mod order_constant;

pub use builtin_formats::{
    BUILTIN_FORMATS_ALL_LANGUAGES, BUILTIN_FORMATS_CN, BUILTIN_FORMATS_MAP_CN,
    BUILTIN_FORMATS_MAP_US, BUILTIN_FORMATS_US, BuiltinFormats, GENERAL,
    MIN_CUSTOM_DATA_FORMAT_INDEX, builtin_format_code, get_builtin_format,
    get_builtin_format_for_locale, switch_builtin_formats, switch_builtin_formats_for_locale,
    switch_builtin_formats_map,
};
pub use easy_excel_constants::{
    EXCEL_MATH_CONTEXT, EXCEL_MATH_CONTEXT_PRECISION, EasyExcelConstants,
};
pub use excel_xml_constants::{
    ATTRIBUTE_LOCATION, ATTRIBUTE_R, ATTRIBUTE_REF, ATTRIBUTE_RID, ATTRIBUTE_S, ATTRIBUTE_T,
    CELL_FORMULA_TAG, CELL_INLINE_STRING_VALUE_TAG, CELL_RANGE_SPLIT, CELL_TAG, CELL_VALUE_TAG,
    DIMENSION_TAG, ExcelXmlConstants, HYPERLINK_TAG, MERGE_CELL_TAG, NS2_CELL_FORMULA_TAG,
    NS2_CELL_INLINE_STRING_VALUE_TAG, NS2_CELL_TAG, NS2_CELL_VALUE_TAG, NS2_DIMENSION_TAG,
    NS2_HYPERLINK_TAG, NS2_MERGE_CELL_TAG, NS2_ROW_TAG, ROW_TAG, SHAREDSTRINGS_NS2_RPH_TAG,
    SHAREDSTRINGS_NS2_SI_TAG, SHAREDSTRINGS_NS2_T_TAG, SHAREDSTRINGS_RPH_TAG, SHAREDSTRINGS_SI_TAG,
    SHAREDSTRINGS_T_TAG, SHAREDSTRINGS_X_RPH_TAG, SHAREDSTRINGS_X_SI_TAG, SHAREDSTRINGS_X_T_TAG,
    X_CELL_FORMULA_TAG, X_CELL_INLINE_STRING_VALUE_TAG, X_CELL_TAG, X_CELL_VALUE_TAG,
    X_DIMENSION_TAG, X_HYPERLINK_TAG, X_MERGE_CELL_TAG, X_ROW_TAG,
};
pub use order_constant::{
    ANNOTATION_DEFINE_STYLE, DEFAULT_DEFINE_STYLE, DEFAULT_ORDER, DEFINE_STYLE, FILL_STYLE,
    OrderConstant,
};
