[package]
name = "easyexcel-demo-rocket"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Rocket native easyexcel-web streaming demo"
repository.workspace = true

[[bin]]
name = "easyexcel-demo-rocket"
path = "src/main.rs"

[dependencies]
easyexcel.workspace = true
easyexcel-rocket.workspace = true
rocket.workspace = true

[lints]
workspace = true
