//! Rust counterpart of Java `com.alibaba.excel.util.BeanMapUtils`.
//!
//! Java generates a CGLIB `BeanMap` at runtime. Rust uses the compile-time
//! [`crate::ExcelRow`] contract and materializes the same field-name lookup
//! without reflection or generated bytecode.

use crate::{ConverterRegistry, ExcelError, ExcelRow};

// 保留历史公开路径，类型的真实实现分别由独立对象模块承载。
pub use super::bean_map::BeanMap;
pub use super::easy_excel_naming_policy::EasyExcelNamingPolicy;

/// 对应 Java：BeanMap.getPropertyType。 Creates a field-name map from an [`ExcelRow`].
///
/// This is the Rust equivalent of `BeanMapUtils.create(bean)` for write and
/// template-fill paths. It executes the same `ExcelRow::to_row` conversion used
/// by production writers instead of returning a type-erased placeholder.
///
/// # Errors
///
/// Returns a conversion error from [`ExcelRow::to_row`], or a format error if a
/// custom implementation returns a different value count than its schema.
pub fn create<T: ExcelRow>(bean: &T) -> Result<BeanMap, ExcelError> {
    create_with_converters(bean, &ConverterRegistry::default())
}

/// 对应 Java：BeanMap.getPropertyType。 Creates a field-name map using an explicit converter registry.
///
/// # Errors
///
/// Returns a conversion error or a schema/value cardinality mismatch.
pub fn create_with_converters<T: ExcelRow>(
    bean: &T,
    converters: &ConverterRegistry,
) -> Result<BeanMap, ExcelError> {
    let schema = T::schema();
    let values = bean.to_row_with_converters(converters)?;
    if values.len() != schema.len() {
        return Err(ExcelError::Format(format!(
            "ExcelRow schema/value length mismatch: schema={}, values={}",
            schema.len(),
            values.len()
        )));
    }
    Ok(BeanMap::from_parts(
        schema
            .iter()
            .zip(values)
            .map(|(column, value)| (column.field, value))
            .collect(),
        schema
            .iter()
            .map(|column| (column.field, column.field_type))
            .collect(),
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{CellValue, ExcelColumn, ExcelWriteMetadata, RowData};

    struct UserRow {
        name: String,
        age: i64,
    }

    impl ExcelRow for UserRow {
        fn schema() -> &'static [ExcelColumn] {
            const COLUMNS: &[ExcelColumn] = &[
                ExcelColumn::new("name", "Name", Some(0), 0, None).with_field_type("String"),
                ExcelColumn::new("age", "Age", Some(1), 1, None).with_field_type("i64"),
            ];
            COLUMNS
        }

        fn write_metadata() -> &'static ExcelWriteMetadata {
            const METADATA: ExcelWriteMetadata = ExcelWriteMetadata::new();
            &METADATA
        }

        fn from_row(_row: &RowData) -> crate::Result<Self> {
            unreachable!("bean map test only exercises write conversion")
        }

        fn to_row(&self) -> crate::Result<Vec<CellValue>> {
            Ok(vec![
                CellValue::String(self.name.clone()),
                CellValue::Int(self.age),
            ])
        }
    }

    #[test]
    fn create_maps_real_excel_row_values_and_declared_types() {
        let map = create(&UserRow {
            name: "Alice".to_owned(),
            age: 18,
        })
        .expect("bean map");

        assert_eq!(
            map.get("name"),
            Some(&CellValue::String("Alice".to_owned()))
        );
        assert_eq!(map.get("age"), Some(&CellValue::Int(18)));
        assert_eq!(map.property_type("name"), Some("String"));
        assert_eq!(map.property_type("age"), Some("i64"));
        assert_eq!(map.len(), 2);
    }

    struct InvalidRow;

    impl ExcelRow for InvalidRow {
        fn schema() -> &'static [ExcelColumn] {
            const COLUMNS: &[ExcelColumn] = &[ExcelColumn::new("value", "Value", Some(0), 0, None)];
            COLUMNS
        }

        fn from_row(_row: &RowData) -> crate::Result<Self> {
            Ok(Self)
        }

        fn to_row(&self) -> crate::Result<Vec<CellValue>> {
            Ok(Vec::new())
        }
    }

    #[test]
    fn create_rejects_schema_value_mismatch_instead_of_silently_dropping_fields() {
        let error = create(&InvalidRow).expect_err("mismatch must fail");
        assert!(error.to_string().contains("schema/value length mismatch"));
    }

    #[test]
    fn user_row_write_metadata_and_unreachable_from_row() {
        // 对应 Java：UserRow 写元数据；from_row 为未实现路径
        let metadata = UserRow::write_metadata();
        assert_eq!(metadata.column_width, None);
        let row = RowData::new(
            "Sheet1",
            0,
            Vec::new(),
            std::sync::Arc::new(std::collections::HashMap::new()),
        );
        let result =
            std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| UserRow::from_row(&row)));
        assert!(result.is_err(), "from_row is intentionally unreachable");
        let result =
            std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| InvalidRow::from_row(&row)));
        assert!(result.is_ok());
    }

    struct EmptyRow;

    impl ExcelRow for EmptyRow {
        fn schema() -> &'static [ExcelColumn] {
            &[]
        }

        fn from_row(_row: &RowData) -> crate::Result<Self> {
            Ok(Self)
        }

        fn to_row(&self) -> crate::Result<Vec<CellValue>> {
            Ok(Vec::new())
        }
    }

    #[test]
    fn iter_is_empty_and_property_type_missing() {
        // 对应 Java：BeanMap 迭代、空判断与缺失属性类型
        let map = create(&UserRow {
            name: "Bob".to_owned(),
            age: 30,
        })
        .expect("bean map");
        let entries: Vec<(&str, &CellValue)> = map.iter().collect();
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[0].0, "age");
        assert!(!map.is_empty());
        assert_eq!(map.property_type("missing"), None);
        assert_eq!(map.get("missing"), None);

        let row = RowData::new(
            "Sheet1",
            0,
            Vec::new(),
            std::sync::Arc::new(std::collections::HashMap::new()),
        );
        let empty_map = create(&EmptyRow::from_row(&row).expect("empty row")).expect("empty map");
        assert!(empty_map.is_empty());
        assert_eq!(empty_map.len(), 0);
        assert!(empty_map.iter().next().is_none());
    }
}
