//! 对应 Java： com.alibaba.excel.util.ClassUtils.
//!
//! Java relies on reflection to map POJO fields to Excel columns. Rust performs the same lookup
//! against metadata generated by `#[derive(ExcelRow)]`.

use std::any::TypeId;

use crate::core::{ExcelColumn, ExcelRow};
use crate::metadata::{
    DateTimeFormatProperty, ExcelContentProperty, FontProperty, NumberFormatProperty, StyleProperty,
};

/// 字段内容属性缓存键。
///
/// 对应 Java：`ClassUtils.ContentPropertyKey`。
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ContentPropertyKey {
    clazz: Option<TypeId>,
    head_class: Option<TypeId>,
    field_name: String,
}

impl ContentPropertyKey {
    #[must_use]
    pub fn new(clazz: Option<TypeId>, head_class: Option<TypeId>, field_name: impl Into<String>) -> Self {
        Self { clazz, head_class, field_name: field_name.into() }
    }
    #[must_use] pub const fn get_clazz(&self) -> Option<TypeId> { self.clazz }
    pub const fn set_clazz(&mut self, value: Option<TypeId>) { self.clazz = value; }
    #[must_use] pub const fn get_head_class(&self) -> Option<TypeId> { self.head_class }
    pub const fn set_head_class(&mut self, value: Option<TypeId>) { self.head_class = value; }
    #[must_use] pub fn get_field_name(&self) -> &str { &self.field_name }
    pub fn set_field_name(&mut self, value: impl Into<String>) { self.field_name = value.into(); }
}

/// 解析字段表时使用的 include/exclude 缓存键。
///
/// 对应 Java：`ClassUtils.FieldCacheKey`。
#[derive(Debug, Clone, Default, PartialEq, Eq, Hash)]
pub struct FieldCacheKey {
    clazz: Option<TypeId>,
    exclude_column_field_names: Vec<String>,
    exclude_column_indexes: Vec<usize>,
    include_column_field_names: Vec<String>,
    include_column_indexes: Vec<usize>,
}

/// Rust 无运行时接口反射；调用方传入 derive/注册阶段已知的 trait 类型键，
/// 本函数按 Java `getAllInterfaces` 语义保序去重。
#[must_use]
pub fn get_all_interfaces(interfaces: Option<&[TypeId]>) -> Option<Vec<TypeId>> {
    let interfaces = interfaces?;
    let mut result = Vec::with_capacity(interfaces.len());
    for interface in interfaces {
        if !result.contains(interface) { result.push(*interface); }
    }
    Some(result)
}

impl FieldCacheKey {
    #[must_use]
    pub fn new(clazz: Option<TypeId>) -> Self { Self { clazz, ..Self::default() } }
    #[must_use] pub const fn get_clazz(&self) -> Option<TypeId> { self.clazz }
    pub const fn set_clazz(&mut self, value: Option<TypeId>) { self.clazz = value; }
    #[must_use] pub fn get_exclude_column_field_names(&self) -> &[String] { &self.exclude_column_field_names }
    pub fn set_exclude_column_field_names(&mut self, value: Vec<String>) { self.exclude_column_field_names = value; }
    #[must_use] pub fn get_exclude_column_indexes(&self) -> &[usize] { &self.exclude_column_indexes }
    pub fn set_exclude_column_indexes(&mut self, value: Vec<usize>) { self.exclude_column_indexes = value; }
    #[must_use] pub fn get_include_column_field_names(&self) -> &[String] { &self.include_column_field_names }
    pub fn set_include_column_field_names(&mut self, value: Vec<String>) { self.include_column_field_names = value; }
    #[must_use] pub fn get_include_column_indexes(&self) -> &[usize] { &self.include_column_indexes }
    pub fn set_include_column_indexes(&mut self, value: Vec<usize>) { self.include_column_indexes = value; }
}

/// 对应 Java：com.alibaba.excel.util.ClassUtils。 Mirrors `com.alibaba.excel.util.ClassUtils#declaredExcelContentProperty`.
///
#[must_use]
pub fn declared_excel_content_property<T: ExcelRow>(
    field_name: &str,
) -> Option<ExcelContentProperty> {
    let column = crate::util::field_utils::get_field::<T>(field_name)?;
    Some(ExcelContentProperty {
        content_style_property: column.content_style.map(StyleProperty::new),
        content_font_property: column.content_font_style.map(FontProperty::build),
        date_time_format_property: DateTimeFormatProperty::build(
            column.effective_date_time_format(),
            column.use_1904_windowing,
        ),
        number_format_property: NumberFormatProperty::build(
            column.effective_number_format(),
            column.number_rounding_mode,
        ),
        date_time_format: column.effective_date_time_format(),
        number_format: column.effective_number_format(),
        field_name: Some(column.field.to_owned()),
        converter_key: None,
    })
}

/// 对应 Java：com.alibaba.excel.util.ClassUtils。 Mirrors `com.alibaba.excel.util.ClassUtils#combineExcelContentProperty`.
///
/// 字段级属性优先于类型级属性，缺失字段回退到类型级属性。
#[must_use]
pub fn combine_excel_content_property(
    type_property: Option<&ExcelContentProperty>,
    field_property: Option<&ExcelContentProperty>,
) -> Option<ExcelContentProperty> {
    let type_property = type_property.cloned().unwrap_or_default();
    let field_property = field_property.cloned().unwrap_or_default();
    if type_property == ExcelContentProperty::default()
        && field_property == ExcelContentProperty::default()
    {
        return None;
    }
    Some(ExcelContentProperty {
        content_style_property: field_property
            .content_style_property
            .or(type_property.content_style_property),
        content_font_property: field_property
            .content_font_property
            .or(type_property.content_font_property),
        date_time_format_property: field_property
            .date_time_format_property
            .or(type_property.date_time_format_property),
        number_format_property: field_property
            .number_format_property
            .or(type_property.number_format_property),
        date_time_format: field_property
            .date_time_format
            .or(type_property.date_time_format),
        number_format: field_property.number_format.or(type_property.number_format),
        field_name: field_property.field_name.or(type_property.field_name),
        converter_key: field_property.converter_key.or(type_property.converter_key),
    })
}

/// 对应 Java：com.alibaba.excel.util.ClassUtils。 Mirrors `com.alibaba.excel.util.ClassUtils#declaredFields`.
///
#[must_use]
pub fn declared_fields<T: ExcelRow>() -> &'static [ExcelColumn] {
    T::schema()
}

/// 对应 Java：com.alibaba.excel.util.ClassUtils。 Mirrors `com.alibaba.excel.util.ClassUtils#removeThreadLocalCache`.
///
/// Java caches reflected `Field` arrays in a `ThreadLocal` for performance.
/// Rust field info is compile-time (`&'static [ExcelColumn]`), no runtime
/// cache needed. The counter allows callers to verify the clear lifecycle.
pub fn remove_thread_local_cache() {
    use std::sync::atomic::{AtomicU32, Ordering};
    static CLEAR_COUNT: AtomicU32 = AtomicU32::new(0);
    CLEAR_COUNT.fetch_add(1, Ordering::Relaxed);
}

#[cfg(test)]
mod tests_extra {
    use super::*;

    #[allow(dead_code)]
    #[derive(crate::ExcelRow)]
    struct MetadataRow {
        #[excel(name = "Value", index = 0, number_format = "0.00")]
        value: f64,
    }

    #[test]
    fn derive_metadata_drives_class_utils() {
        // 对应 Java：ClassUtils 从字段注解解析 ExcelContentProperty。
        let property = declared_excel_content_property::<MetadataRow>("value")
            .expect("derived field metadata");
        assert_eq!(property.number_format, Some("0.00"));
        assert!(declared_excel_content_property::<MetadataRow>("missing").is_none());
        assert_eq!(declared_fields::<MetadataRow>()[0].field, "value");

        let type_property = ExcelContentProperty {
            date_time_format: Some("yyyy-MM-dd"),
            ..ExcelContentProperty::default()
        };
        let combined = combine_excel_content_property(Some(&type_property), Some(&property))
            .expect("combined property");
        assert_eq!(combined.date_time_format, Some("yyyy-MM-dd"));
        assert_eq!(combined.number_format, Some("0.00"));
        assert!(combine_excel_content_property(None, None).is_none());
    }

    #[test]
    fn remove_thread_local_cache_fires() {
        // 对应 Java：ClassUtils.removeThreadLocalCache 生命周期触发
        remove_thread_local_cache();
        remove_thread_local_cache();
        // 不 panic 即通过
    }
}
