[package]
name = "easyexcel"
description = "A Rust implementation of the Alibaba EasyExcel programming model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
easyexcel-core = { path = "../easyexcel-core", version = "0.1.0-alpha.1" }
easyexcel-macro = { path = "../easyexcel-macro", version = "0.1.0-alpha.1" }
easyexcel-reader = { path = "../easyexcel-reader", version = "0.1.0-alpha.1" }
easyexcel-template = { path = "../easyexcel-template", version = "0.1.0-alpha.1" }
easyexcel-writer = { path = "../easyexcel-writer", version = "0.1.0-alpha.1" }

[dev-dependencies]
bigdecimal.workspace = true
calamine.workspace = true
chrono.workspace = true
num-bigint.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
easyexcel-macro = { path = "../easyexcel-macro", version = "0.1.0-alpha.1" }
zip.workspace = true

[lints]
workspace = true
