[package]
name = "easyexcel-support-tide"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "easyexcel-support tide adapter for easyexcel-rust"

[dependencies]
easyexcel = { workspace = true }
easyexcel-core = { workspace = true }
tide = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
urlencoding = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true
